### ISSUE TITLE
Ip or Mac error

### ISSUE THREAD

**Issue by Dengor1984** [smka/homebridge-broadlink-platform#5]
Hello!
I have a this error when start homebridge:

[2017-5-15 18:41:25] Initializing broadlinkMP platform...
[2017-5-15 18:41:25] Created MPs1 s1 Accessory
[2017-5-15 18:41:25] Created MPs2 s2 Accessory
[2017-5-15 18:41:25] Created MPs3 s3 Accessory
[2017-5-15 18:41:25] Created MPs4 s4 Accessory
/usr/lib/node_modules/homebridge-broadlink-platform/index.js:54
if (!this.ip && !this.mac) throw new Error("You must provide a config value for 'ip' or 'mac'.");
^

Error: You must provide a config value for 'ip' or 'mac'.
at BroadlinkAccessory (/usr/lib/node_modules/homebridge-broadlink-platform/index.js:54:38)
at broadlinkMP.accessories (/usr/lib/node_modules/homebridge-broadlink-platform/index.js:35:33)
at Server._loadPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:354:20)
at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:298:16)
at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)

And this is my config.json:

{
"bridge": {
"name": "Homebridge",
"username": "F0:B4:29:CF:B7:F5",
"port": 36640,
"pin": "000-00-001"
},
"platforms": [{
"platform": "AqaraPlatform",
"sid": ["xxxxx"],
"password": ["xxxxx"],
"sensor_names": {"6b4b":"Door Light", "b02613":"Light WC"}
}, 
{
"platform": "yeelight",
"Name": "yeelight"
},
{
"platform": "broadlinkMP",
"accessories": [{
"name": "MP1",
"type": "MP",
"ip": "10.0.1.11"
},
{
"accessory": "PiTemperature",
"name": "Raspberry PI Temperature"
}]
}]}
I have try it with mac or ip, and have this error...
What is wrong and can you help me please?

**Comment by smka** [comment]
@Dengor1984 hi!
You add your "Raspberry PI Temperature" accessory in platform accessory and it shoud be separated.

Try this config:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "F0:B4:29:CF:B7:F5",
        "port": 36640,
        "pin": "000-00-001"
    },
    "accessories": [ //these are separate accessories (remove comment)
        {
        "accessory": "PiTemperature",
        "name": "Raspberry PI Temperature"
        }
    ],
    "platforms": [
        {
            "platform": "AqaraPlatform",
            "sid": ["xxxxx"],
            "password": ["xxxxx"],
            "sensor_names": { "6b4b": "Door Light", "b02613": "Light WC" }
        },
        {
            "platform": "yeelight",
            "Name": "yeelight"
        },
        {
            "platform": "broadlinkMP",
            "accessories": [  //these accessories are only for this platform (remove comment)
                {
                "name": "MP1",
                "type": "MP",
                "ip": "10.0.1.11"
                }
            ]
        }
    ]
}
```

**Comment by Dengor1984** [comment]
Thank you a lot, it works!!!
